import {
  Activity,
  AlertCircle,
  AlertTriangle,
  BarChart3,
  Bell,
  Building2,
  Calendar,
  CheckCircle2,
  CircleDot,
  Clock,
  Command,
  Download,
  Eye,
  FileText,
  Filter,
  FolderOpen,
  Inbox,
  Info,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LogOut,
  PieChart,
  Plus,
  Receipt,
  RefreshCw,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  TrendingUp,
  Upload,
  User,
  Users,
  Vote,
  Wallet,
  Wrench,
  X,
  Zap,
} from "lucide-react";

/** Tree-shakeable icon registry — only the icons Condoos actually uses. */
const ICON_MAP = {
  Activity,
  AlertCircle,
  AlertTriangle,
  BarChart3,
  Bell,
  Building2,
  Calendar,
  CheckCircle2,
  CircleDot,
  Clock,
  Command,
  Download,
  Eye,
  FileText,
  Filter,
  FolderOpen,
  Inbox,
  Info,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LogOut,
  PieChart,
  Plus,
  Receipt,
  RefreshCw,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  TrendingUp,
  Upload,
  User,
  Users,
  Vote,
  Wallet,
  Wrench,
  X,
  Zap,
};

/**
 * Universal icon wrapper — renders a Lucide icon by name.
 * Falls back to null for unknown names (no runtime crash).
 */
export default function Icon({ name, size = 18, className = "", ...props }) {
  const LucideIcon = ICON_MAP[name];
  if (!LucideIcon) return null;
  return <LucideIcon size={size} className={`icon ${className}`} {...props} />;
}
